python ../parlai/scripts/eval_model.py \
    --datatype valid \
    --task dailydialog \
    --model-file ../../checkpoint/blender90M/pretrain/model \
    --batchsize 32 \
    --inference beam \
    --beam-size 10 \
    --beam-min-length 1 \
    --beam-length-penalty 0.65 \
    --beam-block-ngram 3 \
    --beam-context-block-ngram 3 \
    --metrics ppl,bleu,distinct