python ../parlai/scripts/eval_model.py \
    --datatype valid \
    --task dailydialog \
    --model cvae  \
    --model-file /hy-tmp/cvae/dailydialog/model \
    --batchsize 16 \
    --skip-generation False \
    --inference beam \
    --beam-size 10 \
    --beam-length-penalty 0.65 \
    --beam-block-ngram 3 \
    --beam-context-block-ngram 3 \
    --metrics ppl,bleu,distinct