python ../parlai/scripts/train_model.py \
    --task reddit \
    --model cvae \
    --model-file ../../checkpoint/cvae/pretrain/model \
    --batchsize 128 \
    --validation-metric loss \
    --skip-generation True \
    --validation-every-n-epochs 1 \
    --optimizer adamax \
    --learningrate 3e-4 \
    --dict-tokenizer bpe \
    --dict-lower True \
    --embedding-type glove \
    --embeddingsize 300 \
    --hiddensize 512 \
    --latentsize 128 \
    --text-truncate 360 \
    --label-truncate 72 \
    --person-tokens True \
    --num-epochs 15 \
    --validation-patience 1

