python ../parlai/scripts/eval_model.py \
    --datatype valid \
    --model hugging_face/gpt2 \
    --task dailydialog,wizard_of_wikipedia,empathetic_dialogues,convai2 \
    --model-file ../../checkpoint/gpt2/model \
    --skip-generation False \
    --batchsize 16 \
    --inference beam \
    --beam-size 10 \
    --beam-min-length 1 \
    --beam-length-penalty 0.65 \
    --beam-block-ngram 3 \
    --beam-context-block-ngram 3 \
    --metrics ppl,bleu,distinct